"""add mixins on models

Revision ID: dcaf55fb7e5f
Revises: d8e2fc898d67
Create Date: 2025-03-11 11:56:19.337992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcaf55fb7e5f'
down_revision: Union[str, None] = 'd8e2fc898d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tags', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tags', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.drop_column('tags', 'is_deleted')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'is_deleted')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'is_deleted')
    # ### end Alembic commands ###
